
overrides:
    ceph:
        log-whitelist:
          - OSD full dropping all updates
          - OSD near full
        conf:
            osd:
              osd objectstore: memstore
              memstore device bytes: 100000000

tasks:
    - mds_full:
